In [4]:
# make sure to install the latest version of sigmoid_check with pip install sigmoid_check==0.1.3
from sigmoid_check.excalibur import *
import numpy as np

In [5]:
# Given a list of integers `int_list`, create a NumPy array named `array_from_list`.
@check_numpy_1
def numpy_1(int_list):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    array_from_list = np.array(int_list)
    # ABOVE GOES YOUR CODE
    return {"array_from_list": array_from_list}

numpy_1()

✅ Great job! Exercise completed successfully.


In [6]:
# Given two NumPy arrays `array1` and `array2` of the same shape, save their element-wise addition to `added_array`.
@check_numpy_2
def numpy_2(array1, array2):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    added_array = array1 + array2
    # ABOVE GOES YOUR CODE
    return {"added_array": added_array}

numpy_2()

✅ Great job! Exercise completed successfully.


In [7]:
# Given two NumPy arrays `arrayA` and `arrayB`, calculate the element-wise subtraction of `arrayB` from `arrayA` and store the result in `subtracted_array`.
@check_numpy_3
def numpy_3(arrayA, arrayB):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    print(arrayA)
    print(arrayB)
    subtracted_array = arrayB - arrayA
    print(subtracted_array)
    # ABOVE GOES YOUR CODE
    return {"subtracted_array": subtracted_array}

numpy_3()

[1 2 3 4 5]
[5 4 3 2 1]
[ 4  2  0 -2 -4]
[10 20 30 40 50]
[50 40 30 20 10]
[ 40  20   0 -20 -40]
[100 200 300 400 500]
[500 400 300 200 100]
[ 400  200    0 -200 -400]
✅ Great job! Exercise completed successfully.


In [8]:
# Given two NumPy arrays `num_array1` and `num_array2` of the same shape, find their element-wise multiplication and store in `multiplied_array`.
@check_numpy_4
def numpy_4(num_array1, num_array2):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    multiplied_array = num_array1 * num_array2
    # ABOVE GOES YOUR CODE
    return {"multiplied_array": multiplied_array}

numpy_4()

✅ Great job! Exercise completed successfully.


In [9]:
# Given two NumPy arrays `dividend_array` and `divisor_array` of the same shape, perform element-wise division and assign the result to `divided_array`.
@check_numpy_5
def numpy_5(dividend_array, divisor_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    divided_array = dividend_array/divisor_array
    # ABOVE GOES YOUR CODE
    return {"divided_array": divided_array}

numpy_5()

✅ Great job! Exercise completed successfully.


In [10]:
# Given a NumPy array `base_array` and a scalar `exponent`, compute the element-wise exponentiation and store the result in `exponentiated_array`.
@check_numpy_6
def numpy_6(base_array, exponent):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    exponentiated_array = base_array ** exponent
    # ABOVE GOES YOUR CODE
    return {"exponentiated_array": exponentiated_array}

numpy_6()

✅ Great job! Exercise completed successfully.


In [11]:
# Given a list of numbers `float_list`, create a NumPy array named `float_array` with a float data type.
@check_numpy_7
def numpy_7(float_list):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    float_array = np.array(float_list)
    # ABOVE GOES YOUR CODE
    return {"float_array": float_array}

numpy_7()

✅ Great job! Exercise completed successfully.


In [12]:
# Use the list of lists `matrix_data` to create a 2-dimensional NumPy array named `matrix`.
@check_numpy_8
def numpy_8(matrix_data):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    matrix = np.array(matrix_data)
    # ABOVE GOES YOUR CODE
    return {"matrix": matrix}

numpy_8()

✅ Great job! Exercise completed successfully.


In [13]:
# Given a NumPy array `original_array` and the new shape tuple `new_shape`, reshape the array and store it in `reshaped_array`.
@check_numpy_9
def numpy_9(original_array, new_shape):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    reshaped_array = original_array.reshape(new_shape)
    # ABOVE GOES YOUR CODE
    return {"reshaped_array": reshaped_array}

numpy_9()

✅ Great job! Exercise completed successfully.


In [14]:
# Using NumPy's `arange`, generate an array named `range_array` from 0 to `end` with a step of `step`.
@check_numpy_10
def numpy_10(end, step):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    range_array = np.arange(start = 0, stop = end, step=step)
    # ABOVE GOES YOUR CODE
    return {"range_array": range_array}

numpy_10()

✅ Great job! Exercise completed successfully.


In [15]:
# Use NumPy's `linspace` to create an array named `linspace_array` with `num_points` evenly spaced points between `start` and `stop`.
@check_numpy_11
def numpy_11(start, stop, num_points):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    linspace_array = np.linspace(start=start, stop=stop)
    print(linspace_array)
    # ABOVE GOES YOUR CODE
    return {"linspace_array": linspace_array}

numpy_11()

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.83673469
 12.24489796 12.65306122 1

In [16]:
# Create a NumPy array named `zero_array` with a shape specified by `shape` filled with zeros.
@check_numpy_12
def numpy_12(shape):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    zero_array = np.zeros(shape)
    # ABOVE GOES YOUR CODE
    return {"zero_array": zero_array}

numpy_12()

✅ Great job! Exercise completed successfully.


In [17]:
# Create a NumPy array named `ones_array` with a shape given by `shape` filled with ones.
@check_numpy_13
def numpy_13(shape):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    ones_array = np.ones(shape)
    # ABOVE GOES YOUR CODE
    return {"ones_array": ones_array}

numpy_13()

✅ Great job! Exercise completed successfully.


In [18]:
# Given a size `n`, generate an identity matrix named `identity_matrix` of size `n x n`.
@check_numpy_14
def numpy_14(n):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    identity_matrix = np.identity(n=n)
    # ABOVE GOES YOUR CODE
    return {"identity_matrix": identity_matrix}

numpy_14()

✅ Great job! Exercise completed successfully.


In [19]:
# Given a NumPy array `matrix_array`, extract its shape and assign it to `array_shape`.
@check_numpy_15
def numpy_15(matrix_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    array_shape = matrix_array.shape
    # ABOVE GOES YOUR CODE
    return {"array_shape": array_shape}

numpy_15()

✅ Great job! Exercise completed successfully.


In [20]:
# Determine the number of dimensions of the NumPy array `dim_array` and store it in `num_dimensions`.
@check_numpy_16
def numpy_16(dim_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    num_dimensions = dim_array.ndim
    # ABOVE GOES YOUR CODE
    return {"num_dimensions": num_dimensions}

numpy_16()

✅ Great job! Exercise completed successfully.


In [21]:
# Calculate the total number of elements in the NumPy array `elements_array` and store it in `total_elements`.
@check_numpy_17
def numpy_17(elements_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    total_elements = elements_array.size

    # ABOVE GOES YOUR CODE
    return {"total_elements": total_elements}

numpy_17()

✅ Great job! Exercise completed successfully.


In [22]:
# Assign the data type of elements in the NumPy array `type_array` to the variable `element_type`.
@check_numpy_18
def numpy_18(type_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    element_type = type_array.dtype
    # ABOVE GOES YOUR CODE
    return {"element_type": element_type}

numpy_18()

✅ Great job! Exercise completed successfully.


In [23]:
# Compute the memory size (in bytes) of each element in the array `memory_array` and assign it to `element_size`.
@check_numpy_19
def numpy_19(memory_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    element_size = memory_array.itemsize
    # ABOVE GOES YOUR CODE
    return {"element_size": element_size}

numpy_19()

✅ Great job! Exercise completed successfully.


In [24]:
# Convert the integer NumPy array `int_array` to a float array and save it in `float_converted_array`.
@check_numpy_20
def numpy_20(int_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    float_converted_array = int_array.astype('float')
    # ABOVE GOES YOUR CODE
    return {"float_converted_array": float_converted_array}

numpy_20()

✅ Great job! Exercise completed successfully.


In [25]:
# Given a NumPy array `access_array` and an index `index`, assign the element at that index to `selected_element`.
@check_numpy_21
def numpy_21(access_array, index):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    selected_element = access_array[index]
    # ABOVE GOES YOUR CODE
    return {"selected_element": selected_element}

numpy_21()

✅ Great job! Exercise completed successfully.


In [26]:
# Given a NumPy array `slice_array`, extract a slice using `start` and `end` indices, and store it in `sliced_array`.
@check_numpy_22
def numpy_22(slice_array, start, end):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    sliced_array = slice_array[start:end]
    # ABOVE GOES YOUR CODE
    return {"sliced_array": sliced_array}

numpy_22()

✅ Great job! Exercise completed successfully.


In [27]:
# Increase each element of `one_d_array` by 5 and store the result in `increased_array`.
@check_numpy_23
def numpy_23(one_d_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    increased_array = one_d_array + 5
    # ABOVE GOES YOUR CODE
    return {"increased_array": increased_array}

numpy_23()

✅ Great job! Exercise completed successfully.


In [28]:
# Double the values in the 2D array `multi_d_array` and save it in `doubled_array`.
@check_numpy_24
def numpy_24(multi_d_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    doubled_array = multi_d_array * 2
    # ABOVE GOES YOUR CODE
    return {"doubled_array": doubled_array}

numpy_24()

✅ Great job! Exercise completed successfully.


In [29]:
# Given a NumPy array `mask_array` and a `mask_value`, create `filtered_array` containing only the elements of `mask_array` that are greater than `mask_value`.
from numpy import ma
@check_numpy_25
def numpy_25(mask_array, mask_value):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    mask = mask_array == 3
    filtered_array = mask_array[mask]
    # ABOVE GOES YOUR CODE
    return {"filtered_array": filtered_array}

numpy_25()

✅ Great job! Exercise completed successfully.


In [30]:
# Apply masking to the 2D array `multi_mask_array` that keeps all elements greater than the 'condition_value' and store the satisfying elements in `masked_array_2d`.
@check_numpy_26
def numpy_26(multi_mask_array, condition_value):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    mask = multi_mask_array > condition_value
    masked_array_2d = multi_mask_array[mask]
    # ABOVE GOES YOUR CODE
    return {"masked_array_2d": masked_array_2d}

numpy_26()

✅ Great job! Exercise completed successfully.


In [31]:
# Calculate the sum of elements for each column of a 2D array `sum_2d_array` and store it in `column_sums`.
@check_numpy_27
def numpy_27(sum_2d_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    column_sums = sum_2d_array.sum(axis=0)
    # ABOVE GOES YOUR CODE
    return {"column_sums": column_sums}

numpy_27()

✅ Great job! Exercise completed successfully.


In [32]:
# Find the minimum value in the NumPy array `min_array` and assign it to `min_value`.
@check_numpy_28
def numpy_28(min_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    min_value = min_array.min()
    # ABOVE GOES YOUR CODE
    return {"min_value": min_value}

numpy_28()

✅ Great job! Exercise completed successfully.


In [33]:
# Find the maximum value in the NumPy array `max_array` and assign it to `max_value`.
@check_numpy_29
def numpy_29(max_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    max_value = max_array.max()
    # ABOVE GOES YOUR CODE
    return {"max_value": max_value}

numpy_29()

✅ Great job! Exercise completed successfully.


In [34]:
# Calculate the mean of `mean_array` and store it in `mean_value`.
@check_numpy_30
def numpy_30(mean_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    mean_value = mean_array.mean()
    # ABOVE GOES YOUR CODE
    return {"mean_value": mean_value}

numpy_30()

✅ Great job! Exercise completed successfully.


In [35]:
# Calculate the standard deviation of the NumPy array `std_array` and assign it to `std_dev`.
@check_numpy_31
def numpy_31(std_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    std_dev = std_array.std()
    # ABOVE GOES YOUR CODE
    return {"std_dev": std_dev}

numpy_31()

✅ Great job! Exercise completed successfully.


In [36]:
# Compute the square root of each element in `sqrt_array` using `np.sqrt()` and save the result in `sqrt_result`.
@check_numpy_32
def numpy_32(sqrt_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    sqrt_result = np.sqrt(sqrt_array)
    # ABOVE GOES YOUR CODE
    return {"sqrt_result": sqrt_result}

numpy_32()

✅ Great job! Exercise completed successfully.


In [37]:
# Calculate the exponential of each element in `exp_array` with `np.exp()` and store it in `exp_result`.
@check_numpy_33
def numpy_33(exp_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    exp_result = np.exp(exp_array)
    # ABOVE GOES YOUR CODE
    return {"exp_result": exp_result}

numpy_33()

✅ Great job! Exercise completed successfully.


In [38]:
# Compute the natural logarithm of each element in `log_array` with `np.log()` and save it in `log_result`.
@check_numpy_34
def numpy_34(log_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    log_result = np.log(log_array)
    # ABOVE GOES YOUR CODE
    return {"log_result": log_result}

numpy_34()

✅ Great job! Exercise completed successfully.


In [39]:
# Calculate the sine of each element in `sin_array` using `np.sin()` and store the result in `sin_result`.
@check_numpy_35
def numpy_35(sin_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    sin_result = np.sin(sin_array)
    # ABOVE GOES YOUR CODE
    return {"sin_result": sin_result}

numpy_35()

✅ Great job! Exercise completed successfully.


In [40]:
# Compute the cosine of `cos_array` with `np.cos()` and save it in `cos_result`.
@check_numpy_36
def numpy_36(cos_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    cos_result = np.cos(cos_array)
    # ABOVE GOES YOUR CODE
    return {"cos_result": cos_result}

numpy_36()

✅ Great job! Exercise completed successfully.


In [41]:
# Calculate the tangent of each element in `tan_array` using `np.tan()` and save it in `tan_result`.
@check_numpy_37
def numpy_37(tan_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    tan_result = np.tan(tan_array)
    # ABOVE GOES YOUR CODE
    return {"tan_result": tan_result}

numpy_37()

✅ Great job! Exercise completed successfully.


In [42]:
# Transpose the 2D array `transpose_array` using `np.transpose()` and store in `transposed_array`.
@check_numpy_38
def numpy_38(transpose_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    transposed_array = np.transpose(transpose_array)
    print(transpose_array)
    print(transposed_array)
     # ABOVE GOES YOUR CODE
    return {"transposed_array": transposed_array}

numpy_38()

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10 40 70]
 [20 50 80]
 [30 60 90]]
[[100 200 300]
 [400 500 600]
 [700 800 900]]
[[100 400 700]
 [200 500 800]
 [300 600 900]]
✅ Great job! Exercise completed successfully.


In [43]:
# Compute the dot product of `vector1` and `vector2` using `np.dot()` and assign the result to `dot_product_result`.
@check_numpy_39
def numpy_39(vector1, vector2):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    dot_product_result = np.dot(vector1, vector2)
    # ABOVE GOES YOUR CODE
    return {"dot_product_result": dot_product_result}

numpy_39()

✅ Great job! Exercise completed successfully.


In [44]:
# Calculate the inverse of the square matrix `square_matrix` using `np.linalg.inv()` and store it in `inverse_matrix`.
@check_numpy_40
def numpy_40(square_matrix):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    inverse_matrix = np.linalg.inv(square_matrix)
    print(square_matrix)
    print(inverse_matrix)
    # ABOVE GOES YOUR CODE
    return {"inverse_matrix": inverse_matrix}

numpy_40()

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[10 20]
 [30 40]]
[[-0.2   0.1 ]
 [ 0.15 -0.05]]
[[100 200]
 [300 400]]
[[-0.02   0.01 ]
 [ 0.015 -0.005]]
✅ Great job! Exercise completed successfully.


In [45]:
# Find the determinant of the square matrix `det_matrix` using `np.linalg.det()` and assign it to `determinant_value`.
@check_numpy_41
def numpy_41(det_matrix):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    determinant_value = np.linalg.det(det_matrix)
    # ABOVE GOES YOUR CODE
    return {"determinant_value": determinant_value}

numpy_41()

✅ Great job! Exercise completed successfully.


In [46]:
# Concatenate `array_x` and `array_y` vertically using `np.concatenate()` and save the result in `concat_vertical`.
@check_numpy_42
def numpy_42(array_x, array_y):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    concat_vertical = np.concatenate((array_x, array_y), axis=1)
    print(concat_vertical)
    # ABOVE GOES YOUR CODE
    return {"concat_vertical": concat_vertical}

numpy_42()

[[1 2 5 6]
 [3 4 7 8]]
[[10 20 50 60]
 [30 40 70 80]]
[[100 200 500 600]
 [300 400 700 800]]
✅ Great job! Exercise completed successfully.


In [47]:
# Stack `stack_array1` and `stack_array2` horizontally using `np.hstack()` and assign it to `stacked_horizontal`.
@check_numpy_43
def numpy_43(stack_array1, stack_array2):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    stacked_horizontal = np.hstack((stack_array1, stack_array2))
    print(stack_array1)
    print(10 * "-")
    print(stack_array2)
    print(10 * "-")
    print(stacked_horizontal)
    print(20 * "-")
    # ABOVE GOES YOUR CODE
    return {"stacked_horizontal": stacked_horizontal}

numpy_43()

[[1 2]
 [3 4]]
----------
[[5 6]
 [7 8]]
----------
[[1 2 5 6]
 [3 4 7 8]]
--------------------
[[10 20]
 [30 40]]
----------
[[50 60]
 [70 80]]
----------
[[10 20 50 60]
 [30 40 70 80]]
--------------------
[[100 200]
 [300 400]]
----------
[[500 600]
 [700 800]]
----------
[[100 200 500 600]
 [300 400 700 800]]
--------------------
✅ Great job! Exercise completed successfully.


In [48]:
# Add a scalar `scalar_value` to each element of `broadcast_array` using broadcasting and store in `broadcast_result`.
@check_numpy_44
def numpy_44(broadcast_array, scalar_value):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    broadcast_result = broadcast_array + scalar_value
    print(broadcast_array)
    print(10 * "-")
    print(scalar_value)
    print(10 * "-")
    print(broadcast_result)
    print(10 * "--")
    # ABOVE GOES YOUR CODE
    return {"broadcast_result": broadcast_result}

numpy_44()

[[1 2]
 [3 4]]
----------
5
----------
[[6 7]
 [8 9]]
--------------------
[[10 20]
 [30 40]]
----------
50
----------
[[60 70]
 [80 90]]
--------------------
[[100 200]
 [300 400]]
----------
500
----------
[[600 700]
 [800 900]]
--------------------
✅ Great job! Exercise completed successfully.


In [49]:
# Given a 1D array `small_array` and a 2D array `large_array`, utilize broadcasting to add them and store the result in `broadcast_sum`.
@check_numpy_45
def numpy_45(small_array, large_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    broadcast_sum = small_array + large_array
    # ABOVE GOES YOUR CODE
    return {"broadcast_sum": broadcast_sum}

numpy_45()

✅ Great job! Exercise completed successfully.


In [50]:
# Subtract a scalar value `scalar_sub` from each element of `two_d_array`.
@check_numpy_46
def numpy_46(two_d_array, scalar_sub):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    two_d_array -= scalar_sub
    # ABOVE GOES YOUR CODE
    return {"two_d_array": two_d_array}

numpy_46()

✅ Great job! Exercise completed successfully.


In [51]:
# Given dimensions `dim1`, `dim2`, and `dim3`, create a 3D NumPy array named `random_int_array` containing random integers between 0 and 10.
@check_numpy_47
def numpy_47(dim1, dim2, dim3):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    random_int_array = np.random.randint(0, 10, size=dim1*dim2* dim3)
    # ABOVE GOES YOUR CODE
    return {"random_int_array": random_int_array}

numpy_47()

✅ Great job! Exercise completed successfully.


In [52]:
# Convert the 2D array `multi_array` into a 1D array named `flattened`.
@check_numpy_48
def numpy_48(multi_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    flattened = multi_array.flatten(
    )
    # ABOVE GOES YOUR CODE
    return {"flattened": flattened}

numpy_48()

✅ Great job! Exercise completed successfully.


In [53]:
# Given a NumPy array `nonzero_array`, use `np.nonzero()` to find indices of non-zero elements and assign them to `nonzero_indices`.
@check_numpy_49
def numpy_49(nonzero_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    nonzero_indices = np.nonzero(nonzero_array)
    # ABOVE GOES YOUR CODE
    return {"nonzero_indices": nonzero_indices}

numpy_49()

✅ Great job! Exercise completed successfully.


In [54]:
# Create a diagonal matrix `diagonal_matrix` with the given 1D array `diag_elements` using `np.diag()`.
@check_numpy_50
def numpy_50(diag_elements):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    diagonal_matrix = np.diag(diag_elements)
    # ABOVE GOES YOUR CODE
    return {"diagonal_matrix": diagonal_matrix}

numpy_50()

✅ Great job! Exercise completed successfully.


In [55]:
# Update values in `conditional_array` to `new_value` where the condition `np.where_condition` is satisfied, and save it in `updated_array`.
@check_numpy_51
def numpy_51(conditional_array, np_where_condition, new_value):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    print(f"Condition: {np_where_condition}")
    print(f"Conditional array: {conditional_array}")
    print(f"New value: {new_value}")
    updated_array = np.where(np_where_condition,conditional_array, new_value )
    print(updated_array)
    # ABOVE GOES YOUR CODE
    return {"updated_array": updated_array}

numpy_51()

Condition: [ True False  True False  True]
Conditional array: [1 2 3 4 5]
New value: 10
[ 1 10  3 10  5]
Condition: [False  True False  True False]
Conditional array: [10 20 30 40 50]
New value: 100
[100  20 100  40 100]
Condition: [ True False  True False  True]
Conditional array: [100 200 300 400 500]
New value: 1000
[ 100 1000  300 1000  500]
✅ Great job! Exercise completed successfully.


In [56]:
# Given two arrays `max_array_a` and `max_array_b`, compute the element-wise maximum and store it in `element_max`.
@check_numpy_52
def numpy_52(max_array_a, max_array_b):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    element_max = np.maximum(max_array_a, max_array_b)
    # ABOVE GOES YOUR CODE
    return {"element_max": element_max}

numpy_52()

✅ Great job! Exercise completed successfully.


In [57]:
# Calculate the cumulative sum of elements in `cumsum_array` and assign it to `cumulative_sum`.
@check_numpy_53
def numpy_53(cumsum_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    cumulative_sum = np.cumsum(cumsum_array)
    # ABOVE GOES YOUR CODE
    return {"cumulative_sum": cumulative_sum}

numpy_53()

✅ Great job! Exercise completed successfully.


In [58]:
# Extract unique elements from the NumPy array `unique_array` and store them in `unique_elements`.
@check_numpy_54
def numpy_54(unique_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    unique_elements = np.unique(unique_array)
    # ABOVE GOES YOUR CODE
    return {"unique_elements": unique_elements}

numpy_54()

✅ Great job! Exercise completed successfully.


In [59]:
# Sort the array `sort_array` in ascending order and assign it to `sorted_array`.
@check_numpy_55
def numpy_55(sort_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    sorted_array = np.sort(sort_array)
    # ABOVE GOES YOUR CODE
    return {"sorted_array": sorted_array}

numpy_55()

✅ Great job! Exercise completed successfully.


In [60]:
# Compute the intersection of two arrays `intersect_array1` and `intersect_array2` and save it in `intersection`.
@check_numpy_56
def numpy_56(intersect_array1, intersect_array2):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    intersection = np.intersect1d(intersect_array1, intersect_array2)
    # ABOVE GOES YOUR CODE
    return {"intersection": intersection}

numpy_56()

✅ Great job! Exercise completed successfully.


In [61]:
# Join `join_array1`, `join_array2`, and `join_array3` along a new axis using `np.stack()` and store it in `joined_array`.
@check_numpy_57
def numpy_57(join_array1, join_array2, join_array3):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    joined_array = np.stack((join_array1, join_array2, join_array3), axis = 1)
    print(joined_array)
    # ABOVE GOES YOUR CODE
    return {"joined_array": joined_array}

numpy_57()

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[10 40 70]
 [20 50 80]
 [30 60 90]]
[[100 400 700]
 [200 500 800]
 [300 600 900]]
✅ Great job! Exercise completed successfully.


In [62]:
# Split `split_array` into `num_splits` parts using `np.array_split()` and assign the result to `split_parts`.
@check_numpy_58
def numpy_58(split_array, num_splits):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    split_parts = np.array_split(split_array, num_splits)
    # ABOVE GOES YOUR CODE
    return {"split_parts": split_parts}

numpy_58()

✅ Great job! Exercise completed successfully.


In [63]:
# Count elements in `count_array` that are greater than `threshold` and assign the count to `greater_count`.
@check_numpy_59
def numpy_59(count_array, threshold):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    greater_count = np.count_nonzero(count_array > threshold)
    print(greater_count)
    # ABOVE GOES YOUR CODE
    return {"greater_count": greater_count}

numpy_59()

2
❗ The implementation is incorrect or the exercise was not implemented.


In [64]:
count_array= np.array([100, 200, 300, 400, 500])
threshold = 300
greater_count = np.count_nonzero(count_array > threshold)


print(greater_count)

2


In [65]:
# Rotate the 2D array `rotate_array` 90 degrees counterclockwise using `np.rot90()` and store it in `rotated_array`.
@check_numpy_60
def numpy_60(rotate_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    rotated_array = np.rot90(rotate_array)
    # ABOVE GOES YOUR CODE
    return {"rotated_array": rotated_array}

numpy_60()

✅ Great job! Exercise completed successfully.


In [66]:
# Create an array named `random_float_array` with shape `float_shape` containing random floats between 0 and 1.
@check_numpy_61
def numpy_61(float_shape):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    random_float_array = np.random.rand(0,1)
    # ABOVE GOES YOUR CODE
    return {"random_float_array": random_float_array}

numpy_61()

✅ Great job! Exercise completed successfully.


In [67]:
# Compute the median of `median_array` and store it in `median_value`.
@check_numpy_62
def numpy_62(median_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    median_value = np.median(median_array)
    # ABOVE GOES YOUR CODE
    return {"median_value": median_value}

numpy_62()

✅ Great job! Exercise completed successfully.


In [68]:
# Given a complex NumPy array `complex_array`, extract its real and imaginary parts into `real_part` and `imag_part`.
@check_numpy_63
def numpy_63(complex_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    real_part= np.real(complex_array)
    imag_part = np.imag(complex_array)
    # ABOVE GOES YOUR CODE
    return {"real_part": real_part, "imag_part": imag_part}

numpy_63()

✅ Great job! Exercise completed successfully.


In [69]:
# Normalize the array `norm_array` to have values between 0 and 1, storing the result in `normalized_array`.
@check_numpy_64
def numpy_64(norm_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    normalized_array = (norm_array-np.min(norm_array))/(np.max(norm_array)-np.min(norm_array))
    print(f"Normalized array: {normalized_array}")
    # ABOVE GOES YOUR CODE
    return {"normalized_array": normalized_array}

numpy_64()

Normalized array: [0.   0.25 0.5  0.75 1.  ]
Normalized array: [0.   0.25 0.5  0.75 1.  ]
Normalized array: [0.   0.25 0.5  0.75 1.  ]
✅ Great job! Exercise completed successfully.


In [70]:
# Replace negative elements in `replace_array` with `new_value` using `np.where()` and store in `replaced_array`.
@check_numpy_65
def numpy_65(replace_array, new_value):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    replaced_array = np.where(replace_array > 0, replace_array, new_value)
    # ABOVE GOES YOUR CODE
    return {"replaced_array": replaced_array}

numpy_65()

✅ Great job! Exercise completed successfully.


In [71]:
# Calculate the row-wise total sum for `axis_sum_array` and assign the output to `row_sums`.
@check_numpy_66
def numpy_66(axis_sum_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    row_sums = np.sum(axis_sum_array, axis=0)
    # ABOVE GOES YOUR CODE
    return {"row_sums": row_sums}

numpy_66()

✅ Great job! Exercise completed successfully.


In [72]:
# Produce a matrix `random_matrix` with `matrix_shape` dimensions and random integers from 0 to 100.
@check_numpy_67
def numpy_67(matrix_shape):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    print(matrix_shape)
    random_matrix = np.random.randint(0,100, matrix_shape)
    print(random_matrix)
    # ABOVE GOES YOUR CODE
    return {"random_matrix": random_matrix.shape, "random_values": np.any((random_matrix < 0) | (random_matrix > 100))}

numpy_67()

(2, 3)
[[97 58 75]
 [ 9 73 52]]
(3, 4)
[[28 39  5 64]
 [84 27 18  8]
 [27 96 12 97]]
(4, 5)
[[33 24 84 56  9]
 [ 2 78  6 63 51]
 [ 2 13  9 89  8]
 [72 66 81 50 82]]
✅ Great job! Exercise completed successfully.


In [73]:
# Raise each element in `base_power_array` to a power specified in `exp_power_array`, element-wise, and store in `powered_array`.
@check_numpy_68
def numpy_68(base_power_array, exp_power_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    print(f"Exp array: {exp_power_array}")
    print(f"Base array: {base_power_array}")
    powered_array = base_power_array ** exp_power_array
    print(f"Powered array: {powered_array}")
    # ABOVE GOES YOUR CODE
    return {"powered_array": powered_array}

numpy_68()

Exp array: [1 2 3 4 5]
Base array: [1 2 3 4 5]
Powered array: [   1    4   27  256 3125]
Exp array: [1 2 3 4 5]
Base array: [10 20 30 40 50]
Powered array: [       10       400     27000   2560000 312500000]
Exp array: [1 2 3 4 5]
Base array: [100 200 300 400 500]
Powered array: [           100          40000       27000000    25600000000
 31250000000000]
✅ Great job! Exercise completed successfully.


In [74]:
# Detect NaN elements within `nan_array` using `np.isnan()` and assign the position to `nan_indices`.
@check_numpy_69
def numpy_69(nan_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    nan_indices = np.isnan(nan_array)
    # ABOVE GOES YOUR CODE
    return {"nan_indices": nan_indices}

numpy_69()

✅ Great job! Exercise completed successfully.


In [75]:
# Replace `NaN` values in `nan_replace_array` with `specific_value` and create `nan_replaced_array`.
@check_numpy_70
def numpy_70(nan_replace_array, specific_value):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    nan_replaced_array = np.nan_to_num(nan_replace_array, specific_value)
    # ABOVE GOES YOUR CODE
    return {"nan_replaced_array": nan_replaced_array}

numpy_70()

✅ Great job! Exercise completed successfully.


In [76]:
# Construct an upper triangular version of `triangular_matrix` using `np.triu()`.
@check_numpy_71
def numpy_71(triangular_matrix):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    upper_triangular = np.triu(triangular_matrix)
    print(upper_triangular)
    # ABOVE GOES YOUR CODE
    return {"upper_triangular": upper_triangular}

numpy_71()

[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[10 20 30]
 [ 0 50 60]
 [ 0  0 90]]
[[100 200 300]
 [  0 500 600]
 [  0   0 900]]
✅ Great job! Exercise completed successfully.


In [77]:
# Calculate the `percentile_value` percentile of elements in `percentile_array` and set the result to `percentile_result`.
@check_numpy_72
def numpy_72(percentile_array, percentile_value):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    print(percentile_value)
    print(percentile_array)
    percentile_result = np.percentile(percentile_array, percentile_value)
    print(percentile_result)
    # ABOVE GOES YOUR CODE
    return {"percentile_result": percentile_result}

numpy_72()

50
[1 2 3 4 5]
3.0
50
[10 20 30 40 50]
30.0
50
[100 200 300 400 500]
300.0
✅ Great job! Exercise completed successfully.


In [78]:
# Calculate the trace (sum of diagonals) of the matrix `trace_matrix` using `np.trace()`.
@check_numpy_73
def numpy_73(trace_matrix):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    trace_value = np.trace(trace_matrix)
    # ABOVE GOES YOUR CODE
    return {"trace_value": trace_value}

numpy_73()

✅ Great job! Exercise completed successfully.


In [79]:
# Compute the index of the maximum value in `index_max_array` and store it in `max_index`.
@check_numpy_74
def numpy_74(index_max_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    max_index = np.argmax(index_max_array)
    max_index
    # ABOVE GOES YOUR CODE  
    return {"max_index": max_index}

numpy_74()

✅ Great job! Exercise completed successfully.


In [80]:
# Find the index of the minimum value in `index_min_array` and assign it to `min_index`.
@check_numpy_75
def numpy_75(index_min_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    min_index = np.argmin(index_min_array)
    # ABOVE GOES YOUR CODE
    return {"min_index": min_index}

numpy_75()

✅ Great job! Exercise completed successfully.


In [81]:
# Perform an element-wise comparison of `compare_array1` and `compare_array2` using `np.equal()` and assign to `comparison_result`.
@check_numpy_76
def numpy_76(compare_array1, compare_array2):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    comparison_result = np.equal(compare_array1, compare_array2)
    # ABOVE GOES YOUR CODE
    return {"comparison_result": comparison_result}

numpy_76()

✅ Great job! Exercise completed successfully.


In [82]:
# Perform the matrix multiplication between two arrays `mat_mult_a` and `mat_mult_b` and store the result in `matrix_product`.
@check_numpy_77
def numpy_77(mat_mult_a, mat_mult_b):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    matrix_product = mat_mult_a * mat_mult_b
    # ABOVE GOES YOUR CODE
    return {"matrix_product": matrix_product}

numpy_77()

✅ Great job! Exercise completed successfully.


In [83]:
# Extract the diagonal of `diag_matrix` using `np.diag()` and store it in `matrix_diagonal`.
@check_numpy_78
def numpy_78(diag_matrix):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    matrix_diagonal = np.diag(diag_matrix)
    # ABOVE GOES YOUR CODE
    return {"matrix_diagonal": matrix_diagonal}

numpy_78()

✅ Great job! Exercise completed successfully.


In [84]:
# Clip `clip_array` such that all its values fall between `min_clip` and `max_clip`, saving the result in `clipped_array`.
@check_numpy_79
def numpy_79(clip_array, min_clip, max_clip):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    clipped_array = np.clip(clip_array, min_clip, max_clip)
    print(clipped_array)
    # ABOVE GOES YOUR CODE
    return {"clipped_array": clipped_array}

numpy_79()

[2 2 3 4 4]
[20 20 30 40 40]
[200 200 300 400 400]
✅ Great job! Exercise completed successfully.


In [85]:
# Flip `flip_array` along the specified axis `flip_axis` using `np.flip()` and assign to `flipped_array`.
@check_numpy_80
def numpy_80(flip_array, flip_axis):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    flipped_array = np.flip(flip_array, flip_axis)
    # ABOVE GOES YOUR CODE
    return {"flipped_array": flipped_array}

numpy_80()

✅ Great job! Exercise completed successfully.


In [86]:
# Simulate rolling a six-sided die `num_rolls` times to generate an array `dice_rolls`.
@check_numpy_81
def numpy_81(num_rolls):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    dice_rolls = np.random.randint(1, 6, num_rolls)
    print(dice_rolls)
    # ABOVE GOES YOUR CODE
    return {"dice_rolls": dice_rolls}

numpy_81()

[2 5 2 3 4 4 2 5 4 5]
[4 2 5 2 3 5 3 1 4 2 3 1 4 2 2 2 4 5 3 5]
[3 2 4 2 5 2 3 5 1 5 1 4 2 5 3 4 4 2 2 5 2 2 2 4 2 3 5 3 3 3]
✅ Great job! Exercise completed successfully.


In [87]:
# Given two arrays `logical_array_a` and `logical_array_b`, perform a logical `and` operation and save result in `logical_and_result`.
@check_numpy_82
def numpy_82(logical_array_a, logical_array_b):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    logical_and_result = np.logical_and(logical_array_a,logical_array_b)
    # ABOVE GOES YOUR CODE
    return {"logical_and_result": logical_and_result}

numpy_82()

✅ Great job! Exercise completed successfully.


In [88]:
# Reverse the elements in `reverse_array` and store the result in `reversed_array`.
@check_numpy_83
def numpy_83(reverse_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    reversed_array = reverse_array[::-1]
    # ABOVE GOES YOUR CODE
    return {"reversed_array": reversed_array}

numpy_83()

✅ Great job! Exercise completed successfully.


In [89]:
# Compute the cross-product of vectors `vector_a` and `vector_b` and store it in `cross_product_result`.
@check_numpy_84
def numpy_84(vector_a, vector_b):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    cross_product_result = vector_a * vector_b
    # ABOVE GOES YOUR CODE
    return {"cross_product_result": cross_product_result}

numpy_84()

✅ Great job! Exercise completed successfully.


In [90]:
# Use `np.vstack()` to vertically stack `vert_stack_a` and `vert_stack_b` and assign to `vertically_stacked`.
@check_numpy_85
def numpy_85(vert_stack_a, vert_stack_b):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    vertically_stacked = np.vstack((vert_stack_a, vert_stack_b))
    # ABOVE GOES YOUR CODE
    return {"vertically_stacked": vertically_stacked}

numpy_85()

✅ Great job! Exercise completed successfully.


In [91]:
# Create a `checkered_matrix` of size `check_size` with alternating zeros and ones.
@check_numpy_86
def numpy_86(check_size):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    checkered_matrix = np.array([[(i+j)%2 for i in range(check_size[0])] for j in range(check_size[1])])
    print(checkered_matrix)
    # ABOVE GOES YOUR CODE
    return {"checkered_matrix": checkered_matrix}

numpy_86()

[[0 1 0]
 [1 0 1]
 [0 1 0]]
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]
[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]
✅ Great job! Exercise completed successfully.


In [92]:
# Determine the rank of `rank_matrix` using `np.linalg.matrix_rank()`.
@check_numpy_87
def numpy_87(rank_matrix):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    matrix_rank = np.linalg.matrix_rank(rank_matrix)
    # ABOVE GOES YOUR CODE
    return {"matrix_rank": matrix_rank}

numpy_87()

✅ Great job! Exercise completed successfully.


In [93]:
# Extract all non-diagonal elements from `non_diag_matrix` and store them in `off_diagonal`.
@check_numpy_88
def numpy_88(non_diag_matrix):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    print(non_diag_matrix[~np.eye(non_diag_matrix.shape[0],dtype=bool)].reshape(non_diag_matrix.shape[0],-1))
    off_diagonal = non_diag_matrix[~np.eye(non_diag_matrix.shape[0],dtype=bool)].reshape(non_diag_matrix.shape[0],-1)
    print(off_diagonal)
    # ABOVE GOES YOUR CODE
    return {"off_diagonal": off_diagonal}

numpy_88()

[[2]
 [3]]
[[2]
 [3]]
[[20]
 [30]]
[[20]
 [30]]
[[200]
 [300]]
[[200]
 [300]]
✅ Great job! Exercise completed successfully.


In [94]:
# Create a boolean mask `boolean_mask` for the array `mask_less_array` with elements less than `threshold_value`.
@check_numpy_89
def numpy_89(mask_less_array, threshold_value):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    boolean_mask = mask_less_array < threshold_value
    # ABOVE GOES YOUR CODE
    return {"boolean_mask": boolean_mask}

numpy_89()

✅ Great job! Exercise completed successfully.


In [95]:
# Compute the cumulative product of `cumprod_array` and assign the result to `cumulative_product`.
@check_numpy_90
def numpy_90(cumprod_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR 
    print(cumprod_array)
    cumulative_product = np.cumprod(cumprod_array)
    print(cumulative_product)
    # ABOVE GOES YOUR CODE
    return {"cumulative_product": cumulative_product}

numpy_90()

[1 2 3 4 5]
[  1   2   6  24 120]
[10 20 30 40 50]
[      10      200     6000   240000 12000000]
[100 200 300 400 500]
[          100         20000       6000000    2400000000 1200000000000]
✅ Great job! Exercise completed successfully.


In [96]:
# Calculate the absolute differences between `abs_diff_a1` and `abs_diff_a2`, storing the result in `absolute_diff`.
@check_numpy_91
def numpy_91(abs_diff_a1, abs_diff_a2):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    absolute_diff = abs_diff_a1 - abs_diff_a2
    # ABOVE GOES YOUR CODE
    return {"absolute_diff": absolute_diff}

numpy_91()

✅ Great job! Exercise completed successfully.


In [97]:
# Check if `elem_equal_a` and `elem_equal_b` are element-wise equal and store the boolean result in `elementwise_equality`.
@check_numpy_92
def numpy_92(elem_equal_a, elem_equal_b):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE 
    elementwise_equality = np.array_equal(elem_equal_a, elem_equal_b)
    # ABOVE GOES YOUR CODE
    return {"elementwise_equality": elementwise_equality}

numpy_92()

✅ Great job! Exercise completed successfully.


In [98]:
# Create `filtered_within_range` by extracting values from `range_filter_array` that are between `lower_bound` and `upper_bound`.
@check_numpy_93
def numpy_93(range_filter_array, lower_bound, upper_bound):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    filtered_within_range = range_filter_array[(range_filter_array>=5) & (range_filter_array<10)]

    print(filtered_within_range)
    # ABOVE GOES YOUR CODE
    return {"filtered_within_range": filtered_within_range}

numpy_93()

[5]
[]
[]
✅ Great job! Exercise completed successfully.


In [99]:
# Multiply a 1D array `broad_1d` with each row of a 2D array `broad_2d`, and store the result in `broadcast_mult_result`.
@check_numpy_94
def numpy_94(broad_1d, broad_2d):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE

    # ABOVE GOES YOUR CODE
    return {"broadcast_mult_result": broadcast_mult_result}

numpy_94()

❗ The implementation is incorrect or the exercise was not implemented.


In [100]:
# Multiply a 1D array `broad_1d` with each row of a 2D array `broad_2d`, and store the result in `broadcast_mult_result`.
@check_numpy_95
def numpy_95(broad_1d, broad_2d):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    broadcast_mult_result = broad_1d * broad_2d
    # ABOVE GOES YOUR CODE
    return {"broadcast_mult_result": broadcast_mult_result}

numpy_95()

✅ Great job! Exercise completed successfully.


In [101]:
# Apply logarithm base 10 to `log10_array` using `np.log10()` and save the result in `log10_result`.
@check_numpy_96
def numpy_96(log10_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    log10_result = np.log(log10_array)
    # ABOVE GOES YOUR CODE
    return {"log10_result": log10_result}

numpy_96()

✅ Great job! Exercise completed successfully.


In [102]:
# Form a lower triangular matrix from `lower_tri_matrix` using `np.tril()`.
@check_numpy_97
def numpy_97(lower_tri_matrix):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    print(f"Matrix:\n {lower_tri_matrix}")
    lower_triangular = np.tril(lower_tri_matrix)
    print(f"Lower triangular matrix:\n {lower_triangular}")
    # ABOVE GOES YOUR CODE
    return {"lower_triangular": lower_triangular}

numpy_97()

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Lower triangular matrix:
 [[1 0 0]
 [4 5 0]
 [7 8 9]]
Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Lower triangular matrix:
 [[10  0  0]
 [40 50  0]
 [70 80 90]]
Matrix:
 [[100 200 300]
 [400 500 600]
 [700 800 900]]
Lower triangular matrix:
 [[100   0   0]
 [400 500   0]
 [700 800 900]]
✅ Great job! Exercise completed successfully.


In [103]:
# Determine if there are any `True` elements in `bool_array`, assigning the result to `any_true`.
@check_numpy_98
def numpy_98(bool_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    any_true = np.any(bool_array)
    # ABOVE GOES YOUR CODE
    return {"any_true": any_true}

numpy_98()

✅ Great job! Exercise completed successfully.


In [104]:
# Check if all elements in `bool_check_array` are `True`, and store the result in `all_true`.
@check_numpy_99
def numpy_99(bool_check_array):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    all_true = np.all(bool_check_array)
    # ABOVE GOES YOUR CODE
    return {"all_true": all_true}

numpy_99()

✅ Great job! Exercise completed successfully.


In [105]:
bool_check_array = np.array([0, 1, 1, 1])
all_true = np.any(bool_check_array)

all_true

np.True_

In [106]:
# Given two vectors `cos_vector_a` and `cos_vector_b`, calculate the cosine similarity and store it in `cosine_similarity`.
@check_numpy_100
def numpy_100(cos_vector_a, cos_vector_b):
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    cosine_similarity = np.dot(cos_vector_a, cos_vector_b)/(np.linalg.norm(cos_vector_b)*np.linalg.norm(cos_vector_a))
    # ABOVE GOES YOUR CODE
    return {"cosine_similarity": cosine_similarity}

numpy_100()

✅ Great job! Exercise completed successfully.


In [107]:
# Create a function named `reverse_sort_numpy` that takes a NumPy array `arr`, reverses it, removes duplicate elements using NumPy, and returns a sorted version of the array.
@check_numpy_101
def numpy_101():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def reverse_sort_numpy(arr):
        arr = arr[::-1]
        return np.unique(arr)

    # ABOVE GOES YOUR CODE
    return {"reverse_sort_numpy": reverse_sort_numpy}

numpy_101()

✅ Great job! Exercise completed successfully.


In [108]:
# Write a function `normalize_scale_numpy` that takes a NumPy array `arr` and a range `min_val`, `max_val`. Use NumPy to normalize the array to the range [0, 1], then scale it to the given range, and return the resulting array.
@check_numpy_102
def numpy_102():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def normalize_scale_numpy(arr, min_val, max_val):
        return (arr - min_val)/(max_val - min_val)
    # ABOVE GOES YOUR CODE
    return {"normalize_scale_numpy": normalize_scale_numpy}

numpy_102()

✅ Great job! Exercise completed successfully.


In [109]:
# Develop a function `filter_average_numpy` that takes a NumPy array `data` and a threshold `limit`. Use NumPy to filter elements greater than `limit`, compute their average, and return this average.
@check_numpy_103
def numpy_103():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def filter_average_numpy(data, limit):
        data = data >limit
        return np.average(data)
    # ABOVE GOES YOUR CODE
    return {"filter_average_numpy": filter_average_numpy}

numpy_103()

✅ Great job! Exercise completed successfully.


In [110]:
# Create a function `capitalize_count_numpy` that converts a NumPy array of strings `sentence_array` to capitalize each string's first letter, counts the number of elements, and returns a tuple containing the modified array and the count.
@check_numpy_104
def numpy_104():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def capitalize_count_numpy(sentence_array):
        return (np.char.capitalize(sentence_array), np.count_nonzero(sentence_array))
    # ABOVE GOES YOUR CODE
    return {"capitalize_count_numpy": capitalize_count_numpy}

numpy_104()

✅ Great job! Exercise completed successfully.


In [111]:
# Implement a function `clean_categorize_numpy` that processes a NumPy array of strings `items` by stripping spaces and converting to lowercase with NumPy operations, classifying them into 'short' if under 5 characters or 'long' otherwise, returning the counts in a dictionary.
@check_numpy_105
def numpy_105():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def clean_categorize_numpy(items):
        items = np.char.strip(np.char.lower(items))
        print(items)
        print({"short": np.count_nonzero(np.char.str_len(items )<= 5), "long": np.count_nonzero(np.char.str_len(items )> 5)})
        return {"short": np.count_nonzero(np.char.str_len(items )<= 5), "long": np.count_nonzero(np.char.str_len(items )> 5)}

    # ABOVE GOES YOUR CODE
    return {"clean_categorize_numpy": clean_categorize_numpy}

numpy_105()

['apple' 'banana' 'orange' 'pear']
{'short': 2, 'long': 2}
['cat' 'dog' 'bird' 'fish']
{'short': 4, 'long': 0}
['car' 'bus' 'train' 'plane']
{'short': 4, 'long': 0}
✅ Great job! Exercise completed successfully.


In [112]:

# Write a function `remove_outliers_stats_numpy` that takes a NumPy array `num_array`, removes outliers more than two standard deviations from the mean using NumPy, and returns a dictionary with 'mean', 'std', and 'filtered' keys.
import pandas as pd 
@check_numpy_106
def numpy_106():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def remove_outliers_stats_numpy(num_array):
        df =pd.DataFrame(num_array)
        num_array_filtered = df[df.apply(lambda x :(x-x.mean()).abs()<(2*x.std()) ).all(1)]
        print(num_array_filtered)
        return {"mean": np.mean(num_array_filtered), "std": np.std(num_array_filtered), "filtered": num_array_filtered}
        

    # ABOVE GOES YOUR CODE
    return {"remove_outliers_stats_numpy": remove_outliers_stats_numpy}

numpy_106()

    0
0  10
1  12
2  12
3  13
4  12
      0
0     5
1     6
2     7
3     8
4  1000
    0
0  15
1  16
2  15
3  14
4  15
✅ Great job! Exercise completed successfully.


i:\Apps\Anaconda Big\envs\excalibur\Lib\site-packages\numpy\_core\fromnumeric.py:3800: FutureWarning: The behavior of DataFrame.std with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)
i:\Apps\Anaconda Big\envs\excalibur\Lib\site-packages\numpy\_core\fromnumeric.py:3800: FutureWarning: The behavior of DataFrame.std with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)
i:\Apps\Anaconda Big\envs\excalibur\Lib\site-packages\numpy\_core\fromnumeric.py:3800: FutureWarning: The behavior of DataFrame.std with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis

In [113]:
# Create a function `unique_sorted_numpy` that accepts a NumPy array `word_arr`. Use NumPy to remove duplicates, sort them alphabetically, and return the sorted array.
@check_numpy_107
def numpy_107():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def unique_sorted_numpy(word_arr):
        word_arr = np.unique(word_arr)
        return word_arr.sort()
    # ABOVE GOES YOUR CODE
    return {"unique_sorted_numpy": unique_sorted_numpy}

numpy_107()

✅ Great job! Exercise completed successfully.


In [114]:
# Implement a function `format_join_numpy` that takes a NumPy array of strings `words_array`, uses NumPy to title case each word, filter words less than 4 characters, and joins them with a hyphen, returning the final string.
@check_numpy_108
def numpy_108():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def format_join_numpy(words_array):
        print(words_array)
        return np.char.join(np.char.title(words_array)[(np.char.str_len(np.char.title(words_array)) <= 4)],"-")
    # ABOVE GOES YOUR CODE
    return {"format_join_numpy": format_join_numpy}

numpy_108()

['apple' 'not' 'Orange' 'peAR']
['hi' 'there' 'WORLD']
['sun' 'moon' 'Star']
✅ Great job! Exercise completed successfully.


In [115]:
# Write a function `classify_numbers_numpy` that takes a NumPy array `nums`. Use NumPy functions to detect prime numbers and separate them from non-prime numbers, returning both as arrays.
@check_numpy_109
def numpy_109():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def classify_numbers_numpy(nums):
        is_prime = lambda x : x % 2 == 0 
        is_prime = np.vectorize(is_prime)
        non_primes = np.extract(is_prime(nums), nums)
        print(non_primes)
        
        primes = np.extract(non_primes, nums)
        print(primes)
        return (primes, non_primes)
        # ABOVE GOES YOUR CODE
    return {"classify_numbers_numpy": classify_numbers_numpy}

numpy_109()

[ 2  4 10]
[2 3 4]
[18]
[11]
[20 24]
[ 1 19]
✅ Great job! Exercise completed successfully.


In [116]:
# Develop a function `flatten_filter_numpy` that accepts a NumPy array of arrays `list_of_arrays`, flattens it using NumPy, filters out numbers less than 10 using NumPy, and returns the filtered flat array.
@check_numpy_110
def numpy_110():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def flatten_filter_numpy(list_of_arrays):
        return list_of_arrays.flatten()[list_of_arrays.flatten() < 10]
    # ABOVE GOES YOUR CODE
    return {"flatten_filter_numpy": flatten_filter_numpy}

numpy_110()

✅ Great job! Exercise completed successfully.


In [117]:
# Create a function `square_filter_negatives_numpy` that takes a NumPy array `arr`, squares each element using NumPy array operations, removes negative elements, and returns the resulting array.
@check_numpy_111
def numpy_111():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def square_filter_negatives_numpy(arr):
        return np.square(arr)

    # ABOVE GOES YOUR CODE
    return {"square_filter_negatives_numpy": square_filter_negatives_numpy}

numpy_111()

✅ Great job! Exercise completed successfully.


In [118]:
# Implement a function `divide_round_numpy` that takes a NumPy array `values` and a divisor `d`. Divide each element using NumPy, round to two decimal places, and return the resulting array.
@check_numpy_112
def numpy_112():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def divide_round_numpy(values, d):
        return np.round(values /d, 2)
    # ABOVE GOES YOUR CODE
    return {"divide_round_numpy": divide_round_numpy}

numpy_112()

✅ Great job! Exercise completed successfully.


In [119]:
# Write a function `zip_sum_numpy` that takes two NumPy arrays `array1` and `array2`, adds each corresponding element (pair) using NumPy, and returns a new array of these sums.
@check_numpy_113
def numpy_113():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def zip_sum_numpy(array1, array2):
        return array1 + array2

    # ABOVE GOES YOUR CODE
    return {"zip_sum_numpy": zip_sum_numpy}

numpy_113()

✅ Great job! Exercise completed successfully.


In [120]:
# Create a function `binary_classification_numpy` that takes an array `classes` with values `0` and `1`. Use NumPy to count each, calculate their percentages, and return a dictionary with this data.
@check_numpy_114
def numpy_114():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def binary_classification_numpy(classes):
        print()
        return {"0": len(classes[classes == 0])/len(classes) * 100,"1": len(classes[classes == 1])/len(classes) * 100}
    # ABOVE GOES YOUR CODE
    return {"binary_classification_numpy": binary_classification_numpy}

numpy_114()




✅ Great job! Exercise completed successfully.


In [121]:
classes = np.array([0,1,0,1,0])
len(classes[classes == 0])/len(classes) * 100

60.0

In [122]:
# Develop a function `parse_convert_dates_numpy` that processes a NumPy array of date strings `date_strs` in `MM/DD/YYYY` format, converting them into `YYYY-MM-DD` using NumPy, sorting them, and returning the sorted array.
@check_numpy_115
def numpy_115():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def parse_convert_dates_numpy(date_strs):
        date_strs = np.array(date_strs)
        print(np.char.replace(date_strs, "/", "-"))
        return np.char.replace(date_strs, "/", "-")
        
    # ABOVE GOES YOUR CODE
    return {"parse_convert_dates_numpy": parse_convert_dates_numpy}

numpy_115()

['12-25-2022' '01-01-2021' '11-11-2022']
['06-15-2020' '12-24-2019' '10-31-2021']
['09-09-2021' '02-28-2020' '07-04-2023']
✅ Great job! Exercise completed successfully.


In [123]:
# Implement a function `interleave_double_numpy` that accepts two NumPy arrays `arr1` and `arr2`. Use NumPy to interleave elements, double elements from `arr2`, and return the final array.
@check_numpy_116
def numpy_116():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def interleave_double_numpy(arr1, arr2):
        print(np.hstack([arr1,arr2*2]))
        return np.hstack([arr1,arr2*2])

    # ABOVE GOES YOUR CODE
    return {"interleave_double_numpy": interleave_double_numpy}

numpy_116()

[ 1  3  5  4  8 12]
[ 0  7  4 10]
[ 9 20]
✅ Great job! Exercise completed successfully.


In [124]:
# Write a function `group_count_numpy` that takes a NumPy array of strings `str_arr`. Use NumPy to group by length, calculate the occurrence count of each length, and return a dictionary with lengths as keys and counts as values.
@check_numpy_117
def numpy_117():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def group_count_numpy(str_arr):
        arr_ = sorted(str_arr, key=len)
        string_lengths = np.vectorize(len)(arr_)
        lenght_dict = {}
        for i in string_lengths:
            i = int(i)
            if lenght_dict.get(i) is None:
                lenght_dict[i] = 1
            else:
                lenght_dict[i] +=1
        print(lenght_dict)
        return sorted(lenght_dict)
        


    # ABOVE GOES YOUR CODE
    return {"group_count_numpy": group_count_numpy}

numpy_117()

{2: 2, 5: 2}
{2: 2, 3: 1, 4: 2}
{3: 3, 4: 1}
✅ Great job! Exercise completed successfully.


In [125]:


def group_count_numpy(str_arr):
        arr_ = sorted(str_arr, key=len)
        print(arr_)


group_count_numpy(["lol", "ki", "ciupa"])

['ki', 'lol', 'ciupa']


In [126]:
# Create a function `remove_false_combine_numpy` that processes two NumPy boolean arrays `bool_arr1` and `bool_arr2`. Remove `False` entries using NumPy, concatenate them, and return the combined array.
@check_numpy_118
def numpy_118():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def remove_false_combine_numpy(bool_arr1, bool_arr2):
        print(np.concat((bool_arr1[bool_arr1], bool_arr2[bool_arr2])))
        return np.concat((bool_arr1[bool_arr1], bool_arr2[bool_arr2]))

    # ABOVE GOES YOUR CODE
    return {"remove_false_combine_numpy": remove_false_combine_numpy}

numpy_118()

[ True  True  True]
[ True  True  True]
[ True]
✅ Great job! Exercise completed successfully.


In [127]:


def remove_false_combine_numpy(bool_arr1, bool_arr2):
        arr = np.delete((bool_arr1, bool_arr2), False)
        print(arr)


remove_false_combine_numpy(np.array(["True", 'False', "True"]), np.array(["True", 'False', "True"]))

ValueError: boolean array argument obj to delete must be one dimensional and match the axis length of 6

In [ ]:
# Develop a function `check_palindrome_reverse_numpy` that takes a NumPy array of strings `strs`, uses NumPy to filter out non-alphabetic, checks for palindromes, and returns the strings in reverse order.
@check_numpy_119
def numpy_119():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def check_palindrome_reverse_numpy(strs):
        
        for i, str in zip(range(len(strs)), strs):
            if str.isdigit():
                try:
                    strs = np.delete(strs, i)
                except:
                    break
        temp_arr = np.array([])
        for i, str in zip(range(len(strs)), strs):
            if str[::-1] == str:
                    temp_arr = np.append(temp_arr, str)
        return temp_arr[::-1]
            
    # ABOVE GOES YOUR CODE
    return {"check_palindrome_reverse_numpy": check_palindrome_reverse_numpy}

numpy_119()

✅ Great job! Exercise completed successfully.


In [ ]:
strs = np.array(['madam', 'step', 'on', 'no', 'pets'])

def check_palindrome_reverse_numpy(strs):
        
        for i, str in zip(range(len(strs)), strs):
            if str.isdigit():
                try:
                    strs = np.delete(strs, i)
                except:
                    break
        print(range(len(strs)))
        temp_arr = np.array([])
        for i, str in zip(range(len(strs)), strs):
            if str[::-1] == str:
                    strs = np.append(temp_arr, str)
        return strs

check_palindrome_reverse_numpy(strs)

range(0, 5)


array(['madam'], dtype='<U32')

In [ ]:
# Implement a function `find_duplicates_unique_numpy` that accepts a NumPy array `elements`, identifies duplicates using NumPy, separates from unique elements, and returns a tuple of duplicate and unique arrays.
@check_numpy_120
def numpy_120():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def find_duplicates_unique_numpy(elements):
        filter_arr = [np.count_nonzero(elements == i)>1 for i in elements]
        
        return  (np.unique(elements[filter_arr]), np.setdiff1d(elements, elements[filter_arr]))
    # ABOVE GOES YOUR CODE
    return {"find_duplicates_unique_numpy": find_duplicates_unique_numpy}

numpy_120()

✅ Great job! Exercise completed successfully.


In [ ]:
import numpy as np

arr = np.array([1, 2, 3,4,4,4,1])

filter_arr = [np.count_nonzero(arr == i)>1 for i in arr]

newarr = arr[filter_arr]

print(filter_arr)
print(np.unique(newarr))

[True, False, False, True, True, True, True]
[1 4]


In [ ]:
# Write a function `scale_match_numpy` that takes two NumPy arrays `arr_a` and `arr_b`, scales each by their respective maximum with NumPy, and returns `True` if they are identical, otherwise `False`.
@check_numpy_121
def numpy_121():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def scale_match_numpy(arr_a, arr_b):
        return np.array_equal(arr_a/np.max(arr_a),arr_b/np.max(arr_b))
    # ABOVE GOES YOUR CODE
    return {"scale_match_numpy": scale_match_numpy}

numpy_121()

True
True
True
✅ Great job! Exercise completed successfully.


In [ ]:
# Create a function `calculate_ratios_sort_numpy` that takes two NumPy arrays `numers` and `denoms`. Calculate ratios using NumPy, sort them, and return a new array of sorted ratios.
@check_numpy_122
def numpy_122():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def calculate_ratios_sort_numpy(numers, denoms):

        return np.sort((numers/denoms))

    # ABOVE GOES YOUR CODE
    return {"calculate_ratios_sort_numpy": calculate_ratios_sort_numpy}

numpy_122()

[0.5 1.5 2.5]
[1. 2. 4.]
[1.90909091 2.         2.33333333]
✅ Great job! Exercise completed successfully.


In [172]:
# Develop a function `decode_filter_numpy` that processes a NumPy array `codes`, decodes using NumPy string operations, filters messages containing digits, and returns the cleaned array.
@check_numpy_123
def numpy_123():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def decode_filter_numpy(codes):
        digits = [str(x) for x in range(10)]
        temp_arr = np.array([])
        for i in range(len(codes)):
            have_digit = False
            for char in digits:
                if char in codes[i]:
                    have_digit= True
                if have_digit:
                    break
            if have_digit != True:
                temp_arr = np.append(temp_arr, codes[i])
            
            
        print(temp_arr)
        return temp_arr
    # ABOVE GOES YOUR CODE
    return {"decode_filter_numpy": decode_filter_numpy}

numpy_123()

['is' 'test']
['World']
['rocks']
✅ Great job! Exercise completed successfully.


In [183]:
# Implement a function `sync_sum_json_numpy` that takes two JSON-like dictionaries `data1` and `data2`, synchronizes with NumPy by common keys, sums values, and returns the resulting dictionary.
@check_numpy_124
def numpy_124():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def sync_sum_json_numpy(data1, data2):
        keys = [x for x in data1.keys() if x in data2.keys()]
        new_dict = {}
        for key in keys:
            new_dict[key] = data1[key] + data2[key]
        print(new_dict)
        return new_dict
        
    # ABOVE GOES YOUR CODE
    return {"sync_sum_json_numpy": sync_sum_json_numpy}

numpy_124()

{'b': 5, 'c': 7}
{'y': 45}
{'m': 15, 'n': 30}
✅ Great job! Exercise completed successfully.


In [ ]:
# Write a function `tokenize_compare_numpy` that takes two NumPy string arrays `para1` and `para2`, tokenizes using NumPy, calculates the set difference with NumPy, and returns a list of unique words in one array.
@check_numpy_125
def numpy_125():
    # This line is mandatory and should not be removed.
    ex_stat_init = True

    # BELOW GOES YOUR CODE
    def tokenize_compare_numpy(para1, para2): 
        print(np.setdiff1d(np.unique(np.concatenate([line.split() for line in para1])), np.unique(np.concatenate([line.split() for line in para2]))))
        return np.setdiff1d(np.unique(np.concatenate([line.split() for line in para1])), np.unique(np.concatenate([line.split() for line in para2])))
    # ABOVE GOES YOUR CODE
    return {"tokenize_compare_numpy": tokenize_compare_numpy}

numpy_125()

✅ Great job! Exercise completed successfully.
