In [22]:
import numpy as np
import time, sys

In [2]:
numbers = [1,2,3,4,5]
res = [element1 + element2 for element1, element2 in zip(numbers, numbers)]
print(res)

[2, 4, 6, 8, 10]


In [3]:
array = np.array([1,2,3,4])
result = array + array
print(result)

[2 4 6 8]


In [14]:
print(np.int8(42))
print(np.int16(42))
print(np.int64(42))

print(np.float16(42))
print(np.float32(42))
print(np.float64(42))

print(np.complex64(42+42j))

print(np.bool_(True))

42
42
42
42.0
42.0
42.0
(42+42j)
True


In [20]:
my_list = list(range(10000000))
start_time = time.time()
new_list = [element * 2 for element in my_list]
print(f"List time is: {time.time()-start_time}")

my_array = np.arange(10000000)
start_time = time.time()
new_array = my_array * 2
print(f"List time is: {time.time()-start_time}")


List time is: 0.7711484432220459
List time is: 0.030187606811523438


In [25]:
print(sys.getsizeof(my_list))
print(sys.getsizeof(my_array))

80000056
80000112


In [28]:
array_8bit = np.arange(100000, dtype=np.int8)
array_64bit = np.arange(100000, dtype=np.int64)
my_list = list(range(10000000))
start_time = time.time()
modified = array_8bit * 2
print(f"List time is: {time.time()-start_time}")
start_time = time.time()
modified = array_64bit * 2
print(f"List time is: {time.time()-start_time}")
print(sys.getsizeof(array_8bit))
print(sys.getsizeof(array_64bit))

List time is: 0.0
List time is: 0.0
100112
800112


In [44]:
arr_1d = np.array([1,2,3,4])
print("Shape: ", arr_1d.shape)

Shape:  (4,)


In [45]:
arr_2d = np.array([[1,2],[3,4]])
print("Shape: ", arr_2d.shape)

Shape:  (2, 2)


In [46]:
arr_3d = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print("Shape: ", arr_3d.shape)

Shape:  (2, 2, 2)


In [54]:
arr = np.array([1,2,3,4,5,6,7,8])

print(arr)
print(arr.shape)
arr_2 = arr.reshape(2, 4)
print(arr_2)
arr_3 = arr.reshape(2, 2, 2)
print(arr_3)

[1 2 3 4 5 6 7 8]
(8,)
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [69]:
np.arange(0, 10,2) #Works like range in python
np.linspace(10, 50, 30) #
np.zeros((2, 3)) #Creates an array from a tuple with 0
np.ones(((3,4 )))#Creates an array from a tuple with 1
np.eye(7)#input the size of the array, createa a matrice de indentitate
np.random.rand(4, 15)# input the number of rows an columns
np.random.randn(15, 4)# input the number of rows an columns, using normal distribution

array([[-0.08136036, -0.25326916, -0.69873049,  0.3239158 ],
       [ 2.03442615, -0.3583982 ,  1.29297474,  0.4895212 ],
       [-0.03011413,  1.43120518, -0.93866569, -0.74983805],
       [-0.831603  , -1.28857438, -1.4602086 , -0.71002607],
       [-1.10848992, -0.58464868,  0.41855903, -1.23287519],
       [ 2.02910216, -0.35472165, -1.47634965,  0.33871545],
       [ 1.57546303, -1.12213303, -0.27489424, -1.00102255],
       [ 0.20878166,  0.09349618,  1.5012207 ,  0.25440072],
       [-0.71704737,  0.48864998,  0.19488428,  0.12447923],
       [-0.10262599,  1.24835306,  1.01332496, -0.97194557],
       [-0.93193263,  0.22052226,  0.26330278,  0.0288953 ],
       [-0.73871162, -0.31069025, -0.90060069, -0.74178078],
       [-0.27635808,  0.78830092, -0.64797493, -0.88763817],
       [ 0.24756083, -0.61943851,  0.25054536,  0.3090398 ],
       [-0.81716846, -1.08429301, -2.48420458, -1.03699406]])

In [78]:
ceva = np.random.randn(15, 4,3,3,3,3,3, 3,3 ,3 )
ceva.shape

(15, 4, 3, 3, 3, 3, 3, 3, 3, 3)

In [81]:
ceva.ndim # number of dimensions 
ceva.size # number of elements in an arry
ceva.dtype # return the array type
ceva.itemsize #numarul de biti 

8

In [83]:
altceva = np.array([1,2,3,4,5,6,7])
print(altceva[0])