In [102]:
import numpy as np
import time, sys

In [103]:
numbers = [1,2,3,4,5]
res = [element1 + element2 for element1, element2 in zip(numbers, numbers)]
print(res)

[2, 4, 6, 8, 10]


In [104]:
array = np.array([1,2,3,4])
result = array + array
print(result)

[2 4 6 8]


In [1]:
print(np.int8(42))
print(np.int16(42))
print(np.int64(42))

print(np.float16(42))
print(np.float32(42))
print(np.float64(42))

print(np.complex64(42+42j))

print(np.bool_(True))

NameError: name 'np' is not defined

In [106]:
my_list = list(range(10000000))
start_time = time.time()
new_list = [element * 2 for element in my_list]
print(f"List time is: {time.time()-start_time}")

my_array = np.arange(10000000)
start_time = time.time()
new_array = my_array * 2
print(f"List time is: {time.time()-start_time}")


List time is: 0.909343957901001
List time is: 0.027788639068603516


In [107]:
print(sys.getsizeof(my_list))
print(sys.getsizeof(my_array))

80000056
80000112


In [108]:
array_8bit = np.arange(100000, dtype=np.int8)
array_64bit = np.arange(100000, dtype=np.int64)
my_list = list(range(10000000))
start_time = time.time()
modified = array_8bit * 2
print(f"List time is: {time.time()-start_time}")
start_time = time.time()
modified = array_64bit * 2
print(f"List time is: {time.time()-start_time}")
print(sys.getsizeof(array_8bit))
print(sys.getsizeof(array_64bit))

List time is: 0.0010144710540771484
List time is: 0.0010654926300048828
100112
800112


In [109]:
arr_1d = np.array([1,2,3,4])
print("Shape: ", arr_1d.shape)

Shape:  (4,)


In [110]:
arr_2d = np.array([[1,2],[3,4]])
print("Shape: ", arr_2d.shape)

Shape:  (2, 2)


In [111]:
arr_3d = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print("Shape: ", arr_3d.shape)

Shape:  (2, 2, 2)


In [112]:
arr = np.array([1,2,3,4,5,6,7,8])

print(arr)
print(arr.shape)
arr_2 = arr.reshape(2, 4)
print(arr_2)
arr_3 = arr.reshape(2, 2, 2)
print(arr_3)

[1 2 3 4 5 6 7 8]
(8,)
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [113]:
np.arange(0, 10,2) #Works like range in python
np.linspace(10, 50, 30) #
np.zeros((2, 3)) #Creates an array from a tuple with 0
np.ones(((3,4 )))#Creates an array from a tuple with 1
np.eye(7)#input the size of the array, createa a matrice de indentitate
np.random.rand(4, 15)# input the number of rows an columns
np.random.randn(15, 4)# input the number of rows an columns, using normal distribution

array([[-0.83973202, -0.98009647, -2.09262576, -2.49207651],
       [ 1.31198299,  0.48766179,  0.86933323, -0.80783559],
       [ 1.04124963,  0.57147917,  0.60800317,  1.07405705],
       [-0.31536854, -1.01467101,  0.41692323,  0.36366576],
       [ 1.30126433, -0.54990517,  2.15903492, -0.2503124 ],
       [-0.06716279,  0.74585612,  0.39366993, -0.67902118],
       [ 0.89651249,  1.44999386, -2.04828877, -0.26262603],
       [ 0.85656524,  0.29407378,  0.43989208,  0.49383533],
       [-0.17042053,  0.820872  ,  1.55616644, -1.06488223],
       [-0.58760606,  0.18692918,  0.41384272, -0.47496274],
       [-0.03036431, -1.09778308, -1.07491364, -0.25601854],
       [-0.47605894, -0.55566541, -1.11724763, -0.11774346],
       [ 0.48280868,  0.33280241,  0.19489039,  0.62085096],
       [-1.05802466, -0.32387011, -0.06553726,  0.96099321],
       [-1.68802916, -0.5193443 ,  1.99711501,  0.74225996]])

In [114]:
ceva = np.random.randn(15, 4,3,3,3,3,3, 3,3 ,3 )
ceva.shape

(15, 4, 3, 3, 3, 3, 3, 3, 3, 3)

In [115]:
ceva.ndim # number of dimensions 
ceva.size # number of elements in an arry
ceva.dtype # return the array type
ceva.itemsize #numarul de biti 

8

In [116]:
altceva = np.array([1,2,3,4,5,6,7])
print(altceva[1])
print(altceva[-1])
print(altceva[2:-3])

2
7
[3 4]


In [117]:
altceva = np.array([[1,2,3,4], [5,6,7,8]])

print(altceva[1,2])


7


In [118]:
mask = altceva >3
print(mask)
altceva[mask]

[[False False False  True]
 [ True  True  True  True]]


array([4, 5, 6, 7, 8])

In [119]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([1,2,3,4,5,6,7])

print(arr1-arr2)
print(arr1+arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1**arr2)

[0 0 0 0 0 0 0]
[ 2  4  6  8 10 12 14]
[ 1  4  9 16 25 36 49]
[1. 1. 1. 1. 1. 1. 1.]
[     1      4     27    256   3125  46656 823543]


In [120]:
alt = np.array([[1,2,3,4], [5,6,7,8]])
print(np.max(alt))
print(alt.max())
print(alt.max(axis=1))

8
8
[4 8]


# Arrat wide operations


In [121]:
print(alt.max())
print(alt.min())
print(alt.mean())
print(alt.sum())
print(alt.std())

8
1
4.5
36
2.29128784747792


In [139]:
a = np.array(([1,2],[3,4]))
b = np.array(([1,2],[3,4]))
np.dot(a, b)

array([[ 7, 10],
       [15, 22]])

In [130]:
np.sqrt(a)
np.exp(a)
np.log(a)
np.cos(a)
np.sin(a)


array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [132]:
inv_a = np.linalg.inv(a)
print(np.dot(a, inv_a))

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [140]:
det_a = np.linalg.det(a)
print(det_a)

-2.0000000000000004


In [135]:
result = np.concatenate((a, b), axis=0)
result

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [143]:
result = np.hstack((a, b))
result

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [148]:
c = np.array((4))
print("a array:")
print(a)
print("c array:")
print(c)
print("a + c array:")
print(a + c)

a array:
[[1 2]
 [3 4]]
c array:
4
a + c array:
[[5 6]
 [7 8]]


In [150]:
arr1 = np.array([1,2,3])

reshapearr1 = arr1.reshape([1,3])

print(arr1)
print(reshapearr1)

[1 2 3]
[[1 2 3]]


In [151]:
print(arr1 + reshapearr1)
print(reshapearr1 + arr1)

[[2 4 6]]
[[2 4 6]]
